workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 17.0.9
      android_signing:
        - AcademyPittsburgh
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.academypgh.millvalemusicfestival"
        APP_NAME: "Millvale Music Festival"
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install dependencies
        script: |
          yarn install
      - name: Run Jetifier
        script: |
          yarn add jetifier@1.6.6 
          npx jetify
      - name: Build Android release
        script: | 
          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
              # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi
          cd android
          ./gradlew bundleRelease \
            -PversionCode=$UPDATED_BUILD_NUMBER \
            -PversionName=1.6.$UPDATED_BUILD_NUMBER
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: beta
        submit_as_draft: true

  react-native-ios:
    name: React Native iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: academypittsburgh
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.AcademyPGH.MillvaleMusicFestival
      vars:
        BUNDLE_ID: "com.AcademyPGH.MillvaleMusicFestival"
        XCODE_WORKSPACE: "ScheduleApp.xcworkspace"
        XCODE_SCHEME: "ScheduleApp"
        APP_STORE_APPLE_ID: 1460037803
    scripts:
      - name: Install dependencies
        script: |
          yarn install
      - name: Set Info.plist values
        script: | 
          PLIST=$CM_BUILD_DIR/$XCODE_SCHEME/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Set up provisioning profiles
        script: xcode-project use-profiles
      - name: Increment Build Number
        script: |
          cd $CM_BUILD_DIR/ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build iOS ipa
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - internal_testers
        
        submit_to_app_store: false